### ISSUE TITLE
Add about text in topic _index page

### ISSUE THREAD

**Issue by YvonneKallberg** [ScilifelabDataCentre/RDM-guidelines#14]
https://github.com/ScilifelabDataCentre/RDM-guidelines/blob/main/content/topic/_index.md

Write some introductory text about the topics, (what is meant by a topic, click on the link to find information about a certain topic etc.)

Also, when a human page is available, add link to it and remove all commented text in the markdown file.

**Comment by elinkronander** [comment]
I had written some about text and changed the title from Topic to Guidelines by topic but after changing the display to tiles I decided to revert.

If we want an about text this is a draft:
`

`> Some of the research data management topics spans over several phases of the data life cycle or requires special attention for other reasons. Click on either of the links below to get guidance around a specific research data management topic. `

`

**Comment by KatarinaOjeforsStark** [comment]
Suggested  some changes in the text. 
**Please note that** some of the research data management **(RDM)** topics spans over several phases of the data life cycle or **may require** special attention for other reasons. **In order to get** guidance around a specific research data management topic, **you may click on the specific links listen below.**

**Comment by YvonneKallberg** [comment]
Since an update has been made (and deployed) to the topics page, I will close this issue.
