### ISSUE TITLE
update the plan phase page

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#286]
Suggestion from a support project

**Comment by YvonneKallberg** [comment]
In order to remember what this was about: When writing an application for funding (European), they want to have small snippets of text to copy and paste into their application, regarding services and resources that they plan to use in the future project, (and I guess how these will facilitate good DM practices and FAIRness?). A suggestion is to at least collect links to the resources, with a short text, on the plan page. Data platform have a collection, also on compute infrastructure resources, and the DM flyer has short texts.

**Comment by elinkronander** [comment]
Should we also include a statement on budgeting for RDM costs in the application?

**Comment by YvonneKallberg** [comment]
https://rdmkit.elixir-europe.org/costs_data_management

**Comment by YvonneKallberg** [comment]
We will not provide application texts, our recommendation is to write a DMP and get guidance from there. DSW KM will get a review + refresh during autumn, ensuring that also links to e.g. data platform catalogues are included. It is up to applicants to visit the services and resources, and collect suitable information from there.

We can still revisit the plan page, and update with the minimal mentioned in earlier comments (links to external resources)

**Comment by annaasklof** [comment]
Decided to close due to feasibility issues.
