### ISSUE TITLE
link to infectious disease toolkit

### ISSUE THREAD

**Issue by elinkronander** [ScilifelabDataCentre/RDM-guidelines#383]

**Comment by elinkronander** [comment]
Add a link to the main page rather than several links to specific topics/subpages.
Find a suitable page to add it to.

**Comment by YvonneKallberg** [comment]
The toolkit covers all phases, and some topics e.g. human data, but if we add the main page as resource and then set all phases, it will not show up in the phase pages since we have set a limit to not display such 'all encompassing' resources (think it had to do with there being too many sources displayed then, too 'noisy'). 

Hence, we might need to rethink either the limit (and see if some of the resources that makes pages noisy can have fewer page tags) or not link to main page (at least not only) but rather do some cherry picking among the topics on the main page [IDTk](https://www.infectious-diseases-toolkit.org/), similar to what we have for RDMkit.
